name: CI/CD whois client

on:
    push:
        branches:
            - "build-test"

jobs:
    # Check if applicaion builds
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build the docker_compose
              run: docker-compose up -d --build

            - name: Build the application
              run: docker-compose exec -u node -T whois_frontend npm run build
